from __future__ import annotations
from fastapi import APIRouter
from app.routes import logs,  nodes,  memory,  memory_browser,  sessions,  sessions_live,  agents, agents_live, tasks, analytics, recovery, replay, health, health_multiagent, error_logs, budget_alerts, sync, gateway_events, activity, approvals, approvals_ui, skills, gateways, tags, boards, cron, exec_approvals, webhooks, organizations, audit, agent_registry, traces, model_performance, system_health, autonomy

api_router = APIRouter(prefix="/api")

api_router.include_router(agent_registry.router, prefix="/agents", tags=["agent-registry"])
api_router.include_router(agents.router, prefix="/agents", tags=["agents"])
api_router.include_router(agents_live.router, prefix="/agents", tags=["agents-live"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(recovery.router, prefix="/recovery", tags=["recovery"])
api_router.include_router(replay.router, prefix="/replay", tags=["replay"])
api_router.include_router(health.router, prefix="/health", tags=["health"])
api_router.include_router(health_multiagent.router, prefix="/health/multiagent", tags=["health-multiagent"])
api_router.include_router(error_logs.router, prefix="/error-logs", tags=["error-logs"])
api_router.include_router(budget_alerts.router, prefix="/budget", tags=["budget"])
api_router.include_router(sync.router, prefix="/sync", tags=["sync"])
api_router.include_router(gateway_events.router, prefix="/gateway-events", tags=["gateway-events"])
api_router.include_router(activity.router, prefix="/activity", tags=["activity"])
api_router.include_router(approvals.router, prefix="/approvals", tags=["approvals"])
api_router.include_router(approvals_ui.router, prefix="/approvals-ui", tags=["approvals-ui"])
api_router.include_router(skills.router, prefix="/skills", tags=["skills"])
api_router.include_router(gateways.router, prefix="/gateways", tags=["gateways"])
api_router.include_router(tags.router, prefix="/tags", tags=["tags"])
api_router.include_router(boards.router, prefix="/boards", tags=["boards"])
api_router.include_router(cron.router, prefix="/cron", tags=["cron"])
api_router.include_router(exec_approvals.router, prefix="/exec-approvals", tags=["exec-approvals"])
api_router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
api_router.include_router(organizations.router, prefix="/organizations", tags=["organizations"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(sessions.router, prefix="/sessions", tags=["sessions"])
api_router.include_router(sessions_live.router, prefix="/sessions", tags=["sessions-live"])
api_router.include_router(memory.router, prefix="/memory", tags=["memory"])
api_router.include_router(memory_browser.router, prefix="/memory", tags=["memory-browser"])
api_router.include_router(nodes.router, prefix="/nodes", tags=["nodes"])
api_router.include_router(logs.router, prefix="/logs", tags=["logs"])
api_router.include_router(traces.router, prefix="/traces", tags=["traces"])
api_router.include_router(model_performance.router, prefix="/models", tags=["model-performance"])
api_router.include_router(system_health.router, prefix="/system", tags=["system"])
api_router.include_router(autonomy.router, prefix="/autonomy", tags=["autonomy"])
